version: '3.8'

services:
  app:
    container_name: express-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  app-prod:
    container_name: express-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=production
